version: '3'

services:
  db:
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password
    env_file: 
       - .env
    #   MYSQL_DATABASE: hashview 
    ports:
      - "3306:3306"
    networks:
      db:
        aliases:
          - sql
  webapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: hashview-server 
    # command: foreman start 
    # Make pry-byebug actually work
    tty: true
    stdin_open: true
    environment:
      RACK_ENV: development
    volumes:
      - .:/src
    ports:
      - "443:4567"
    depends_on:
      - db
      - redis 
    networks:
      - web
      - db
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - web 
  #smtp:
  #  image: namshi/smtp
  #  ports:
      

networks:
  web:
  db:
